theme: jekyll-theme-architect
title: ANKI für Schüler (und Eltern)
description: |
   Informationen für Schüler und Eltern zum Lernen mit "Karteikarten" mit dem
   OpenSource programm Anki; aufbereitet von einem Vater, der sich und seine
   Kinder täglich mit Anki drangsaliert...