theme: jekyll-theme-architect
title: ANKI für Schüler (und Eltern)
description: |
   Informationen für Schüler und Eltern zum Lernen mit dem
   OpenSource-Programm Anki. Aufbereitet von einem Vater, der sich selbst und seine
   Kinder täglich mit Anki drangsaliert ...